[package]
name = "pstools"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A simple interface for generating PostScript files"
repository = "https://github.com/profmadden/pstools_r"

[dependencies]
argh = "0.1.13"
scan_fmt = "0.2.6"
